const express = require('express');
// const fileUpload = require('express-fileupload');
const app = express();

//db
const db = require('./dbconfig/configDb');

app.use(express.urlencoded({extended: false}))
// app.use(fileUpload());

const registerRouter = require("./router/register");
const signInRouter = require("./router/signin");
const personRouter = require('./router/person');
const documentRouter = require('./router/docs');
const branchRouter = require('./router/branch');
const fileRouter = require('./router/file');
const documentOne = require('./router/documentone');
// const branchRouter = require("./router/branch")

const port = process.env.PORT || 3000;

//create endpoints for sql db
app.use('/api/v1/signin', signInRouter);
app.use('/api/v1/register', registerRouter);
app.use('/api/v1/persons', personRouter);
app.use('/api/v1/documents', documentRouter);
app.use('/api/v1/branches', branchRouter);
app.use('/api/v1/files', fileRouter);
app.use('/api/v1/documentone', documentOne);
//create endpoints for google drive db

//For sql db
/*** 
 * *****
 * Customers endpoint
 *  post req
 * NOTE: For post request id shoild be auto generated by the api
 *      api/v1/institution
 *          api/v1/institution/private
 *              /person
 *              /branch
 *              /document
 *              /filenos
 *              /documentone
 *              /documenttwo
 *              /documentthree
 *              /document...
 *
 *          api/v1/institution/govt
 *              /person
 *              /branch
 *              /document
 *              /filenos
 *              /documentone
 *              /documenttwo
 *              /documentthree
 *              /document...
 *              ...
 *  get req
 *      api/v1/institution
 *          api/v1/institution/private
 *              /person
 *              /person/:id
 *              /branch
 *              /branch/:id
 *              /document
 *              /document/:id
 *              /filenos
 *              /filenos/:id
 *              /documentone
 *              /documentone/:id
 *              /documenttwo
 *              /documenttwo/:id
 *              /documentthree
 *              /documentthree/:id
 *              /document...
 *              /document.../:id

 *
 *          api/v1/institution/public
 *              /person
 *              /person/:id
 *              /branch
 *              /branch/:id
 *              /document
 *              /document/:id
 *              /filenos
 *              /filenos/:id
 *              /documentone
 *              /documentone/:id
 *              /documenttwo
 *              /documenttwo/:id
 *              /documentthree
 *              /documentthree/:id
 *              /document...
 *              /document.../:id
 *              ...
 * 
 *  patch req & delete request
 *          api/v1/institution/private
 *              /person/:id
 *              /branch/:id
 *              /document/:id
 *              /filenos/:id
 *              /documentone/:id
 *              /documenttwo/:id
 *              /documentthree/:id
 *              /document.../:id
 * 
 *          api/v1/institution/public
 *              /person/:id
 *              /branch/:id
 *              /document/:id
 *              /filenos/:id
 *              /documentone/:id
 *              /documenttwo/:id
 *              /documentthree/:id
 *              /document.../:id
 * *******
 * Admin Endpoint
 * 
 * ***/

// app.post('api/v1/company', (req, res) => {
//     const file = req.file.mypic
//     res.get
// })

// app.get('/', (req, res) => {
//     res.send({
//         id: "ijomah",
//         no: 080
//     })
// });

app.listen(port, () => console.log(`listening on port: ${port}`));

module.exports = app;