const express = require('express');
//const fileUpload = require('express-fileupload');
const app = express();



//app.use(fileUpload());

const registerRouter = require("./router/register");
const signInRouter = require("./router/signin");
const personRouter = require('./router/person');
const categoryRouter = require('./router/category');
const branchRouter = require('./router/branch');
const fileRouter = require('./router/file');
const categoryOne = require('./router/categoryone');
// const branchRouter = require("./router/branch")

const port = process.env.PORT || 3000;

//create endpoints for sql db
app.use('/api/v1/signin', signInRouter);
app.use('/api/v1/register', registerRouter);
app.use('/api/v1/persons', personRouter);
app.use('/api/v1/category', categoryRouter);
app.use('/api/v1/branches', branchRouter);
app.use('/api/v1/files', fileRouter);
app.use('/api/v1/categoryone', categoryOne);
//create endpoints for google drive db

//For sql db
/*** 
 * *****
 * Customers endpoint
 *  post req
 * NOTE: For post request id shoild be auto generated by the api
 *      api/v1/institution
 *          api/v1/institution/private
 *              /person
 *              /branch
 *              /category
 *              /filenos
 *              /categoryone
 *              /categorytwo
 *              /categorythree
 *              /category...
 *
 *          api/v1/institution/govt
 *              /person
 *              /branch
 *              /category
 *              /filenos
 *              /categoryone
 *              /categorytwo
 *              /categorythree
 *              /category...
 *              ...
 *  get req
 *      api/v1/institution
 *          api/v1/institution/private
 *              /person
 *              /person/:id
 *              /branch
 *              /branch/:id
 *              /category
 *              /category/:id
 *              /filenos
 *              /filenos/:id
 *              /categoryone
 *              /categoryone/:id
 *              /categorytwo
 *              /categorytwo/:id
 *              /categorythree
 *              /categorythree/:id
 *              /category...
 *              /category.../:id

 *
 *          api/v1/institution/public
 *              /person
 *              /person/:id
 *              /branch
 *              /branch/:id
 *              /category
 *              /category/:id
 *              /filenos
 *              /filenos/:id
 *              /categoryone
 *              /categoryone/:id
 *              /categorytwo
 *              /categorytwo/:id
 *              /categorythree
 *              /categorythree/:id
 *              /category...
 *              /category.../:id
 *              ...
 * 
 *  patch req & delete request
 *          api/v1/institution/private
 *              /person/:id
 *              /branch/:id
 *              /category/:id
 *              /filenos/:id
 *              /categoryone/:id
 *              /categorytwo/:id
 *              /categorythree/:id
 *              /category.../:id
 * 
 *          api/v1/institution/public
 *              /person/:id
 *              /branch/:id
 *              /category/:id
 *              /filenos/:id
 *              /categoryone/:id
 *              /categorytwo/:id
 *              /categorythree/:id
 *              /category.../:id
 * *******
 * Admin Endpoint
 * 
 * ***/

// app.post('api/v1/company', (req, res) => {
//     const file = req.file.mypic
//     res.get
// })

// app.get('/', (req, res) => {
//     res.send({
//         id: "ijomah",
//         no: 080
//     })
// });

app.listen(port, () => console.log(`listening on port: ${port}`));

module.exports = app;